general {
    border_size = 2
    gaps_in = 0
    gaps_out = 0
    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.inactive_border = rgba(595959aa)
    resize_on_border = true
}

decoration {
    rounding = 0
    drop_shadow = false
    blur {
        enabled = false
    }
}

animations {
    enabled = false
}

dwindle {
    force_split = 2
    preserve_split = true
}

input {
    follow_mouse = 0
}

$mainMod = SUPER

bind = $mainMod, q, exit,
bind = $mainMod, t, exec, alacritty
bind = $mainMod, c, killactive,
bind = $mainMod, e, exec, nautilus
bind = $mainMod, v, togglefloating,
bind = $mainMod, f, fullscreen,
bind = $mainMod, d, exec, rofi -theme ~/.dots/home/configs/rofi/launcher.rasi -show
bind = $mainMod, p, exec, hyprpicker --autocopy --format=hex

bind = $mainMod, l, movefocus, l
bind = $mainMod, h, movefocus, r
bind = $mainMod, j, movefocus, u
bind = $mainMod, k, movefocus, d

bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9

bind = $mainMod, F1, movetoworkspace, 1
bind = $mainMod, F2, movetoworkspace, 2
bind = $mainMod, F3, movetoworkspace, 3
bind = $mainMod, F4, movetoworkspace, 4
bind = $mainMod, F5, movetoworkspace, 5
bind = $mainMod, F6, movetoworkspace, 6
bind = $mainMod, F7, movetoworkspace, 7
bind = $mainMod, F8, movetoworkspace, 8
bind = $mainMod, F9, movetoworkspace, 9

bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

bindl = , XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bindl = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindl = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioPrev, exec, playerctl previous
bindl = , XF86AudioNext, exec, playerctl next

windowrulev2 = suppressevent maximize, class:.*

# Disable border if there is only one window.
windowrulev2 = noborder, onworkspace:w[t1]
