{flakeLib, ...}: let
  c = flakeLib.colors;
in
  # xml
  ''
    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
    <plist version="1.0">
        <dict>
            <key>author</key>
            <string>Me</string>
            <key>colorSpaceName</key>
            <string>sRGB</string>
            <key>name</key>
            <string>flake</string>
            <key>semanticClass</key>
            <string>flake.theme</string>
            <key>settings</key>
            <array>
                <dict>
                    <key>settings</key>
                    <dict>
                        <key>background</key>
                        <string>${c.bg}</string>
                        <key>foreground</key>
                        <string>${c.fg}</string>
                    </dict>
                </dict>
                <dict>
                    <key>scope</key>
                    <string>keyword</string>
                    <key>settings</key>
                    <dict>
                        <key>foreground</key>
                        <string>${c.syntax.keyword}</string>
                        <key>fontStyle</key>
                        <string>bold</string>
                    </dict>
                </dict>
                <dict>
                    <key>scope</key>
                    <string>keyword.operator</string>
                    <key>settings</key>
                    <dict>
                        <key>foreground</key>
                        <string>${c.syntax.operator}</string>
                        <key>fontStyle</key>
                        <string></string>
                    </dict>
                </dict>
                <dict>
                    <key>scope</key>
                    <string>punctuation</string>
                    <key>settings</key>
                    <dict>
                        <key>foreground</key>
                        <string>${c.syntax.punctuation}</string>
                    </dict>
                </dict>
                <dict>
                    <key>scope</key>
                    <string>comment</string>
                    <key>settings</key>
                    <dict>
                        <key>foreground</key>
                        <string>${c.syntax.comment}</string>
                    </dict>
                </dict>
                <dict>
                    <key>scope</key>
                    <string>constant.numeric</string>
                    <key>settings</key>
                    <dict>
                        <key>foreground</key>
                        <string>${c.syntax.number}</string>
                    </dict>
                </dict>
                <dict>
                    <key>scope</key>
                    <string>string, punctuation.definition.string</string>
                    <key>settings</key>
                    <dict>
                        <key>foreground</key>
                        <string>${c.syntax.string}</string>
                    </dict>
                </dict>
                <dict>
                    <key>scope</key>
                    <string>constant.character.escape</string>
                    <key>settings</key>
                    <dict>
                        <key>foreground</key>
                        <string>${c.fg}</string>
                    </dict>
                </dict>
                <dict>
                    <key>scope</key>
                    <string>entity.name, support.type, support.class</string>
                    <key>settings</key>
                    <dict>
                        <key>foreground</key>
                        <string>${c.syntax.type}</string>
                    </dict>
                </dict>
                <dict>
                    <key>scope</key>
                    <string>entity.name.function, support.function, variable.function</string>
                    <key>settings</key>
                    <dict>
                        <key>foreground</key>
                        <string>${c.syntax.function}</string>
                    </dict>
                </dict>
                <!-- Diff -->
                <dict>
                    <key>scope</key>
                    <string>meta.diff, meta.diff.header</string>
                    <key>settings</key>
                    <dict>
                        <key>foreground</key>
                        <string>${c.diff.header}</string>
                    </dict>
                </dict>
                <dict>
                    <key>scope</key>
                    <string>markup.deleted</string>
                    <key>settings</key>
                    <dict>
                        <key>foreground</key>
                        <string>${c.diff.removed}</string>
                    </dict>
                </dict>
                <dict>
                    <key>scope</key>
                    <string>markup.inserted</string>
                    <key>settings</key>
                    <dict>
                        <key>foreground</key>
                        <string>${c.diff.added}</string>
                    </dict>
                </dict>
                <dict>
                    <key>scope</key>
                    <string>markup.changed</string>
                    <key>settings</key>
                    <dict>
                        <key>foreground</key>
                        <string>${c.diff.changed}</string>
                    </dict>
                </dict>
            </array>
            <key>uuid</key>
            <string>uuid</string>
        </dict>
    </plist>
  ''
