-- local harpoon = require("harpoon")
--
-- harpoon:setup()
--
-- vim.keymap.set("n", "ma", function()
--   harpoon:list():add()
-- end)
-- vim.keymap.set("n", "me", function()
--   harpoon.ui:toggle_quick_menu(harpoon:list())
-- end)
--
-- for idx, key in ipairs({ "h", "t", "n", "s" }) do
--   vim.keymap.set("n", string.format("m%s", key), function()
--     harpoon:list():replace_at(idx)
--   end)
--   vim.keymap.set("n", string.format("<c-%s>", key), function()
--     harpoon:list():select(idx)
--   end)
-- end
